config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :mainTech, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new 
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit 
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:i])
  
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def project_params
      params.require(:project).permit(:title, :gitLink, :siteLink, :mainTech, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
  <%= form_with model: @project do |form| %>
    <div>
      <%=form.label :title %><br>
      <%=form.text_field :title %>
      <% @project.errors.full_messages_for(:title).each do |msg| %>
        <div><%= msg %> </div>
        <% end %>
    </div>

    <div>
      <%=form.label :gitLink %><br>
      <%=form.text_field :gitLink %>
    </div>

    <div>
      <%=form.label :siteLink %><br>
      <%=form.text_field :siteLink %>
    </div>

    <div>
      <%=form.label :mainTech %><br>
      <%=form.text_field :mainTech %>
      <% @project.errors.full_messages_for(:mainTech).each do |msg| %>
        <div><%= msg %> </div>
        <% end %>
    </div>

    <div>
      <%=form.label :body %><br>
      <%=form.text_area :body %>
      <% @project.errors.full_messages_for(:body).each do |msg| %>
        <div><%= msg %> </div>
        <% end %>
    </div>

    <div>
      <%= form.submit %>
    </div>
    
  <% end %>

app/views/projects/edit.html.erb
<h1> Edit Project </h1>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1> All Project </h1>

<ul> 
  <% @projects.each do |project| %>
    <li>
      <a href="<%= project_path(project) %>">
        <%= project.title %>
      </a>
    </li>
  <% end %>

  <a href="/projects/new">
    Add A Project
  </a>
  
</ul>

app/views/projects/new.html.erb
<h1> Add Project </h1> 

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<h1> <%= @project.title %> </h1> 
<p> <%= @project.body %> </p>

<ul>
<li><%= link_to "Edit", edit_project_url(@project) %> </li>
<li><%= button_to "Destroy", project_path(@project), method: :delete,
            data: { method_turbo_confirm: "Are you sure?" }
 %></li>
 </ul>